settings:
  disable_player_file_saving: false
  use_player_move_event: false
  playerChunkUnload: true
  mobAi: true
  doLeafDecay: false
  light-updates-max-ms-per-tick: 30
License: ZUHEP-OC5BR-9KGQO-XQSWK-1WZOK
